import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf
import cv2
from knowledge_base import chatbot_response
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import io
import warnings
import h5py
import json
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
from PIL import Image as PILImage
import pandas as pd

warnings.filterwarnings("ignore")

MODEL_PATH = "autism.h5"

with h5py.File(MODEL_PATH, "r") as f:
    config_data = f.attrs.get("model_config")

    if isinstance(config_data, bytes):
        config = json.loads(config_data.decode("utf-8"))
    else:
        config = json.loads(config_data)

    for layer in config["config"]["layers"]:
        layer_config = layer.get("config", {})

        if "batch_shape" in layer_config:
            layer_config["batch_input_shape"] = layer_config.pop("batch_shape")

        if "dtype" in layer_config:
            layer_config.pop("dtype")

        if "optional" in layer_config:
            layer_config.pop("optional")

        if "quantization_config" in layer_config:
            layer_config.pop("quantization_config")

model = tf.keras.models.model_from_config(config)
model.load_weights(MODEL_PATH, by_name=True, skip_mismatch=True)

CLASS_NAMES = ["ASD Likely", "Not ASD"]

# ================= PREDICTION =================
def predict_image(img):
    img = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2GRAY)
    img = cv2.resize(img, (224, 224))

    img_array = np.expand_dims(img, axis=(0, -1))
    img_array = img_array / 255.0

    preds = model.predict(img_array)
    confidence = float(np.max(preds))
    label = CLASS_NAMES[np.argmax(preds)]

    return label, confidence

# pdf
def generate_pdf_report(user_name, label, confidence, recommendations):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width / 2, height - 80, "ASD Detection Report")

    c.setFont("Helvetica", 12)
    c.drawString(80, height - 130, f"Name: {user_name or 'User'}")
    c.drawString(80, height - 150, f"Result: {label}")
    c.drawString(80, height - 170, f"Confidence: {confidence * 100:.2f}%")

    text = c.beginText(80, height - 210)
    text.textLines(recommendations)
    c.drawText(text)

    c.save()
    buffer.seek(0)
    return buffer

# sidebar
st.set_page_config(page_title="Autism Support App", layout="wide")

st.sidebar.title("🧠 Autism Support App")

app_mode = st.sidebar.radio(
    "Select a feature:",
    ["About Autism", "Image Prediction", "Video Analysis", "Chat with Assistant", "Find Nearby Doctors"]
)


def generate_pdf_report(user_name, label, confidence, recommendations, original_img=None):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>ASD Detection Report</b>", styles["Title"]))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph(f"<b>Name:</b> {user_name or 'User'}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Result:</b> {label}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Confidence:</b> {confidence * 100:.2f}%", styles["Normal"]))
    elements.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    elements.append(Spacer(1, 20))

    if original_img is not None:
        pil_img = PILImage.fromarray(original_img)
        img_buffer = io.BytesIO()
        pil_img.save(img_buffer, format="PNG")
        img_buffer.seek(0)

        elements.append(Paragraph("<b>Analyzed Image:</b>", styles["Heading2"]))
        elements.append(Spacer(1, 10))
        elements.append(RLImage(img_buffer, width=250, height=250))
        elements.append(Spacer(1, 20))

    elements.append(Paragraph("<b>Recommendation:</b>", styles["Heading2"]))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(recommendations, styles["Normal"]))

    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Generated by Autism AI System", styles["Italic"]))

    doc.build(elements)
    buffer.seek(0)

    return buffer

# ABOUT
if app_mode == "About Autism":
    st.title("🌈 Understanding Autism Spectrum Disorder (ASD)")
    st.markdown("""
        Autism Spectrum Disorder (ASD) is a **neurodevelopmental condition** that affects communication, behavior, and social interaction.
        People with autism may have unique strengths and differences that make them special in their own way.
        """)
    st.subheader("🧩 Common Characteristics")
    st.markdown("""
        - Difficulty with social interaction and communication
        - Repetitive behaviors or routines
        - Deep interest in specific topics
        - Sensory sensitivities (sound, light, texture)
        """)
    st.subheader("💡 Early Identification & Support")
    st.markdown("""
        Early diagnosis and behavioral therapy can make a significant difference in a child’s development.
        Family support, special education, and consistent therapy are key factors in helping individuals thrive.
        """)
    st.success("💬 You can now chat with our Autism Assistant or upload an image for analysis using the sidebar!")


#  IMAGE
elif app_mode == "Image Prediction":
    st.title("🧩 Image Analysis")

    uploaded_file = st.file_uploader("Upload image", type=["jpg", "png"])

    if uploaded_file:
        img = Image.open(uploaded_file)
        st.image(img)

        name = st.text_input("Enter your name")  # ✅ FIX

        if st.button("Predict"):
            label, confidence = predict_image(img)
            st.success(f"{label} ({confidence:.2f})")

            rec = "Consult a specialist." if label == "ASD Likely" else "Continue monitoring."

            if name:
                pdf = generate_pdf_report(
                    name,
                    label,
                    confidence,
                    rec,
                    original_img=np.array(img)
                )

                st.download_button(
                    label="📄 Download Image Report",
                    data=pdf,
                    file_name="ASD_Image_Report.pdf",
                    mime="application/pdf"
                )
            else:
                st.warning("Please enter your name")

#  VIDEO
elif app_mode == "Video Analysis":
    st.title("🎥 Autism Video Analysis")

    uploaded_video = st.file_uploader("Upload a video", type=["mp4", "avi", "mov"])

    if uploaded_video is not None:
        st.video(uploaded_video)

        if st.button("Analyze Video"):
            import tempfile

            tfile = tempfile.NamedTemporaryFile(delete=False)
            tfile.write(uploaded_video.read())

            cap = cv2.VideoCapture(tfile.name)

            total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            progress_bar = st.progress(0)

            frame_predictions = []
            frame_count = 0

            while cap.isOpened():
                ret, frame = cap.read()
                if not ret:
                    break

                progress = int((frame_count / total_frames) * 100)
                progress_bar.progress(progress)

                if frame_count % 10 == 0:
                    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                    frame = cv2.resize(frame, (224, 224))

                    frame = np.expand_dims(frame, axis=(0, -1))
                    frame = frame / 255.0

                    pred = model.predict(frame)
                    frame_predictions.append(pred)

                frame_count += 1

            cap.release()
            progress_bar.progress(100)

            # Final prediction
            if frame_predictions:
                avg_pred = np.mean(frame_predictions, axis=0)
                confidence = float(np.max(avg_pred))
                label = CLASS_NAMES[np.argmax(avg_pred)]


                st.session_state["video_label"] = label
                st.session_state["video_confidence"] = confidence


            if "video_label" in st.session_state:
                label = st.session_state["video_label"]
                confidence = st.session_state["video_confidence"]

                st.success(f"Final Prediction: {label}")
                st.info(f"Confidence: {confidence:.2f}")

# CHAT
elif app_mode == "Chat with Assistant":
    st.title("💬 Chatbot")

    user_input = st.text_input("Ask something")

    if st.button("Send") and user_input:
        response = chatbot_response(user_input)
        st.write("Bot:", response)

# DOCTORS
elif app_mode == "Find Nearby Doctors":
    st.title("🏥 Find Nearby Autism Specialists")
    st.markdown(
        "Locate doctors, therapists, or clinics near your area that specialize in Autism Spectrum Disorder (ASD).")

    st.markdown("### 🌍 Step 1: Share Your Location")
    st.info("You can enter your city manually to search for specialists.")

    location = st.text_input("Enter your city or area name:", placeholder="e.g., Chennai, Tamil Nadu")

    if st.button("🔎 Search Nearby Doctors"):
        if not location.strip():
            st.warning("Please enter a location first.")
        else:
            st.success(f"Showing Autism specialists near **{location}**:")

            # Google Maps search
            google_maps_url = f"https://www.google.com/maps/search/autism+specialist+near+{location.replace(' ', '+')}"
            st.markdown(f"[🗺️ Open in Google Maps]({google_maps_url})")

            data = pd.DataFrame({
                'Clinic Name': ['Clinic A', 'Clinic B'],
                'Latitude': [12.9716, 13.0827],
                'Longitude': [77.5946, 80.2707]
            })
        data = data.rename(columns={'Latitude': 'lat', 'Longitude': 'lon'})
        st.map(data)

        st.caption(
            "💡 The map above shows sample data for visualization. Use the Google Maps link above for live results.")
